UNRECOVERABLE
LOAD DATA
APPEND INTO TABLE TBUTCA_PESSOA_BUREAU_N
(
NUM_CPF_CNPJ             position(       1       :       14      ),
TIP_PESSOA               position(       377     :       377     ),
NUM_CNPJ_RAIZ            position(       1       :       8       ),
NUM_CNPJ_FILIAL          position(       9       :       12      ),
DAC_CNPJ                 position(       13      :       14      )
)
